### ISSUE TITLE
Voice Calling Sample!

### ISSUE THREAD

**Issue by onpointhealth** [Azure-Samples/communication-services-dotnet-quickstarts#1]
There is no support for Voice Calling. Why not release the docs for the REST API and let the community help out?

**Comment by alex-kwan** [comment]
@onpointhealth I was wondering if you could provide some clarification on your question? are you looking for a way to do a video call via as dotnet c# application? (Utilizing a C# SDK to do the calling?)

We do have a calling sample which is a dotnet server and a typescript (react) front end to do a voice call? However in this case the magic is in the front end utilizing the JS Calling SDK.
https://github.com/Azure-Samples/communication-services-web-calling-hero

**Comment by onpointhealth** [comment]
Thanks for quick response! I want to do the calling from a Xamarin.Forms Android / iOS app. Hence I need a .NET Core / Standard SDK.

**Comment by alex-kwan** [comment]
@onpointhealth 

I am curious if this repo can help you out!
https://github.com/Laerdal/Xamarin.AzureCommunicationCalling

It is definitely super cool to see the community start to build communication experiences with us :) Hopefully this repo helps^

**Comment by ddematheu2** [comment]
@onpointhealth can we close this thread? Was the issue solved?

**Comment by Munde** [comment]
I think it will be nice if you will provide a support for xamarin forms as this it will help us xamarin developers to consume and try the services in a seamless way

**Comment by markti** [comment]
I agree with @Munde. Xamarin.Forms should have support.

**Comment by ddematheu2** [comment]
Thank you for the feedback. Will share with our team.
