### ISSUE TITLE
Get chat thread id by teams meeting link format like "https://teams.microsoft.com/meet/{$id}?p={$passcode}"

### ISSUE THREAD

**Issue by riddlexu** [Azure-Samples/communication-services-dotnet-quickstarts#179]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
Currently, the teams meeting uri has new format like "https://teams.microsoft.com/meet/{$id}?p={$passcode}". But the current example  asserts that the meeting link should be like ""https://teams.microsoft.com/l/meetup-join/19:meeting_Nzk5@thread.v2". So in the example code, we cannot get the chat thread id by new format teams meeting link.

- The code in [dotnet example](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/blob/13b2121d62ebe2c074a5df6c7e655bbef4d3a386/ChatTeamsInteropQuickStart/src/ChatTeamsInteropQuickStart/MainPage.xaml.cs#L261).
![image](https://github.com/user-attachments/assets/cbecdfdc-0558-4781-aa80-504d6481d595)

There are similar example in nodejs example. And seems we can get chat thread id without calling Graph Api as [doc](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-windows) described (We don't want to call Graph Api because it may lead to some permission stuff).
- The code in [nodejs example](https://github.com/Azure-Samples/communication-services-javascript-quickstarts/blob/6f05e0d1c28739545322b59dcaed9efee7715458/join-chat-to-teams-meeting/Chat%20Experience/client.js#L80C7-L80C20). 

So are there any way to get the chat thread id in dotnet by new format meeting link? Thanks. 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 11
### Versions
>

**Comment by vhuseinova-msft** [comment]
Hi @riddlexu!
Thank you for posting the question. 
Currently, there is no way to obtain the threadId from a new Teams short link using the .Net SDK. The recommended approach for .Net projects is to utilize the Graph API. For more details, please refer to [this link](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/chat/meeting-interop?pivots=platform-windows).
For feature request, please use https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858.
