### ISSUE TITLE
Gap in documentation - association of azure identity with device to receive incoming call

### ISSUE THREAD

**Issue by ahmadtofeeq** [Azure-Samples/communication-services-dotnet-quickstarts#40]
I was reading Azure communication services. As stated in production, a server is recommended to generate an azure identity. 
Lets assume we have two client A (web App), B ( Mobile app) and an application server.
client A and B generated their azure identities. Now Client A wants to make a call to B, it request access token from Application server and try to call B. App server will provide B azure identity as well. But as of now, azure identity is no where linked to device B. On what basis call from A will reach to B?
Do we need to initiate anything in client sdk about azure identity?

**Comment by petrsvihlik** [comment]
Hi @ahmadtofeeq ,
I really appreciate your feedback and I agree that this could have been explained more explicitly.

To answer your questions:
Yes, that's correct, both parties need to initialize the `callAgent` (or `CallAgent` in .NET) to be able to talk to each other.

According to [the docs](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?pivots=platform-windows#authenticate-the-client):

>Initialize a `CallAgent` instance with a User Access Token which will enable us to make and receive calls.

> The CallAgent is used to start and manage calls.

The call agent emits events for incoming calls. You can hook into these events and handle the calls.

Exchanging of the identities (making sure A knows the ID of B and vice versa) is the responsibility of your application.

**Comment by ahmadtofeeq** [comment]
@petrsvihlik  Thanks for a quick response. I go agree, exchanging identities is our application server responsibility. Application server generate identity and token and send back to client. So i assume that CallAgent will associate that token with the device to make a logical mapping and allow azure to identity device.  Am i correct?

Second thing, Token are short lived, so we need to poll frequently to generate a new token? Will this not cause the bad experience for mobile app where app can live in background for forever

**Comment by petrsvihlik** [comment]
> @petrsvihlik Petr Svihlik FTE Thanks for a quick response. I go agree, exchanging identities is our application server responsibility. Application server generate identity and token and send back to client. So i assume that CallAgent will associate that token with the device to make a logical mapping and allow azure to identity device. Am i correct?

Yes, the token contains information about the identity and the CallAgent takes care of the device mapping.
 
> Second thing, Token are short lived, so we need to poll frequently to generate a new token? Will this not cause the bad experience for mobile app where app can live in background for forever

There is a built-in mechanism for refreshing tokens which you should utilize. Please follow the [best practices](https://docs.microsoft.com/en-us/azure/communication-services/concepts/credentials-best-practices?tabs=javascript#token-refreshing) and [.NET-specific code samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/communication/Azure.Communication.Common#create-a-credential-with-a-callback) to implement the token refresh callback. Basically, the autorefreshing makes sure that the credential object always contains a fresh token with a long enough validity (expiration time).
