### ISSUE TITLE
No property to embed an image to email using EmailMessage with Azure Communication Service

### ISSUE THREAD

**Issue by sammym1** [Azure-Samples/communication-services-dotnet-quickstarts#51]
> Please provide us with the following information:
> ---------------------------------------------------------------

Ask is for below sample

[communication-services-dotnet-quickstarts](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts)/[SendEmailAdvanced](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/main/SendEmailAdvanced)/SendEmailWithAttachments/

### Need to Embed an image in the mail body.
I am using EmailMessage and EmailMessage does not have "AlternateViews" property.

### It's a ask and not an issue

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by matthohn-msft** [comment]
Thank you @sammym1. Acknowledging this ask, we will be looking into this scenario more

**Comment by MagnusWagner-WIT** [comment]
I would also be interested in this feature.

**Comment by lnehrin** [comment]
So without the ability to get the CID of an attachment, how **does** one embed an image into the HTML of an email??  I've have zero luck trying to inline base64.

**Comment by IberianTops** [comment]
Same here. 

**Same with PowerAutomate Online, the Send Email action doesn't allow CID to work because the field Content-ID is not defined and passed through, hence you can't reference the attached images. And base64 for example is not supported by Gmail.** 

Weird since I believe Outlook desktop uses CID when you're sending embedded images. Yet their own automation system, that they've developed, doesn't support it.

**Comment by gguillen** [comment]
+1 need this

**Comment by krisbart** [comment]
+1

**Comment by eltiano** [comment]
+1

**Comment by EdgarsM** [comment]
+1

**Comment by yartman** [comment]
+1 here also

**Comment by Carlstorm** [comment]
+1

**Comment by roaddirect-development** [comment]
+1

**Comment by ErikRBergman** [comment]
+1

**Comment by zzundalek** [comment]
+1

**Comment by eredwan** [comment]
+1
This is a bit sad that this did not come standard. I have found most of the Microsoft Azure tech that I have evaluated to be subpar at best. Many times things are missing like this. I was evaluating PowerApps and it had trouble showing all available tables for a given connection to Oracle capped at a max array of 2047 or so. It would only show tables in alphabetical order so I was missing any tables after the letter B. When contacting support they had no solution. 
Anyways, enough of my tangent, please add this feature to embed images to email body.

**Comment by bpruissen** [comment]
+1

**Comment by tcrevier** [comment]
I agree, I also need this functionality to use it more broadly.  This doesn't seem like it would be difficult add, it is in so many other email sending APIs.

**Comment by KunalAdu** [comment]
At last, I've found a solution. Instead of using CID, incorporate an img tag containing base 64 content. This will insert an image in the E-mail HTML body.
**Inside content and html** (https://github.com/Azure-Samples/communication-services-javascript-quickstarts/blob/main/send-email-advanced/send-email-attachments/send-email-attachments.js#L22)

For more details, please refer to: https://learn.microsoft.com/en-us/power-automate/desktop-flows/how-to/add-images-email-messages

**Comment by tcrevier** [comment]
@KunalAdu Thanks!  That is a reasonable work around for the short term...

**Comment by jfperren** [comment]
+1! Also need this

**Comment by leonardogazdek** [comment]
[KunalAdu](https://github.com/KunalAdu) this will not work in gmail unfortunately.

This is a very basic feature, unacceptable that the service doesn't support it.

**Comment by crlandwe** [comment]
+1

**Comment by newportg** [comment]
This is needed now please

**Comment by sabifa** [comment]
Open for nearly 1.5 years and still no response?

**Comment by freedomsuites** [comment]
+1 : I cannot embed generated images targeted at some email clients (e.g. GMail) without this feature.  And no, the workaround provided by @KunalAdu does not work on all email clients.

https://www.caniemail.com/features/image-base64/

**Comment by sebastianblesgen** [comment]
+1.
CID is for us the easiest to not fall in SPAM issues with external links and base64 is not supported by all clients (gmail for instance).

I know we are talking about MS technologies here but our clients do not care what we are using and we can't force everyone to move to Microsoft Outlook.

**Comment by olcaybuyan** [comment]
+1

**Comment by scayze** [comment]
+1

**Comment by crlandwe** [comment]
Bump, as other users stated, we cannot control what email services our users decide to use. please add gmail support.

**Comment by tanguy3165** [comment]
+1

**Comment by aardvark79** [comment]
+1

**Comment by AlexAmin** [comment]
+1

**Comment by kubop** [comment]
+1 it baffles my mind that such basic feature is not supported after almost 2 years of making a feature request and many people actually wanting it

**Comment by jake-wickstrom** [comment]
+1

**Comment by haseeb0807** [comment]
Workaround can be host the images and access by their URL in `src` param of `<img src=""/>`
**Note** - SVG images will not show up, it has to be .png

**Comment by wojbron-blue** [comment]
+1

**Comment by gayan-d** [comment]
This is a very serious limitation of azure communication services. Unbelivable that it's not supported even after two years.

**Comment by podvlada** [comment]
+1

**Comment by gako** [comment]
+1

**Comment by aeromac** [comment]
Any updates from anyone at Microsoft about this? or workarounds that work in all mail clients?

**Comment by natekimball-msft** [comment]
Hello everyone,

I realize this thread has been open for quite some time without a response from anyone on our team, and for that, we sincerely apologize. This feature has certainly been a long time coming, but we're very pleased to announce that inline attachments are now available with the most recent release of our REST API and language SDKs. You can find more information on its usage in our [inline attachments documentation](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-advanced/send-email-with-inline-attachments?tabs=connection-string&pivots=programming-language-csharp), in addition to links to our GitHub sample apps so you can get up & running quickly.

Here are links to the releases for each language SDK:
.NET (NuGet): [Azure.Communication.Email 1.1.0-beta.2](https://www.nuget.org/packages/Azure.Communication.Email/1.1.0-beta.2)
JavaScript (NPM): [@azure/communication-email 1.0.1-beta.1](https://www.npmjs.com/package/@azure/communication-email/v/1.0.1-beta.1?activeTab=readme)
Java (Maven): [azure-communication-email 1.1.0-beta.1](https://central.sonatype.com/artifact/com.azure/azure-communication-email/1.1.0-beta.1/versions)
Python (PyPi): [azure-communication-email 1.0.1b1](https://pypi.org/project/azure-communication-email/1.0.1b1/)

In addition, you can test the feature yourself from your Azure portal. Follow the guidance [here](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp) to create a new Communications resource, or optionally, use an existing one. Head to the resource overview, then Email > Try Email, and give it a test drive. 

Again, on behalf of all of us, we're sorry for the lack of communication. We hope you enjoy using this feature and our service. If you have any questions, concerns, or suggestions, feel free to contact me through here or reach out to the team at acsemail@microsoft.com and we will be sure to answer < 2 years (usually within a few days). Thank you and enjoy!

**Comment by vc2023** [comment]
Why the thread has been closed?
The problem wasn't solved, at least not for google.
