### ISSUE TITLE
Creating Event Subscription, In Azure port deployment is getting to fail with following error

### ISSUE THREAD

**Issue by v-pradda** [Azure-Samples/communication-services-dotnet-quickstarts#73]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/main/CallAutomation_SimpleIvr
- Followed steps mentioned for creating Event Subscription, In Azure port deployment is getting to fail with following error.
- Followed the steps mentioned .
- 
![Screenshot_IncomingcallEvenSubscription_Failing](https://user-images.githubusercontent.com/94802801/206336422-3b7335a9-18e4-46a7-92a5-69c80d3b739f.png)

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by moirf** [comment]
This issue have been fixed.
